# ----------------- LLMs begin --------------------

# The owner of the 'Large Language Model' that should be used. OpenAI by default due to ChatGPT.
# If you type "OpenAI":
# - Fill up the 'openAI_API_key'
llmModel: "OpenAI"

# Token for accessing OpenAI's models. You may generate an API token/key here: https://platform.openai.com/account/api-keys
# At the moment of writing this, you must have a paid subscription in order for your API keys to work
openAI_API_key: ""

# The ChatGPT model that this plugin should use
chatGPTModel: "gpt-3.5-turbo"
# ----------------- LLMs end --------------------

# The maximum distance (in blocks) in which agents can chat with each other. Agents who are too far away cannot engage in conversations
maxChatRange: 5

# Whether all chats between Social Agents should be broadcasted to the entire server as if it were normal players chatting, or if
# the chats should be solely displayed on top of agent's heads
chatBroadcast: Yes

# Whether agents should be loaded after a server restart.
# If set to 'No', then all agents disappear after a restart. They're still saved in the MineSocieties/social_agents directory, but
# the plugin will not automatically load them once it starts again.
loadSavedAgents: Yes

# Whether agents can start querying the LLM to choose actions after a server restart. This should be
# off by default as to not immediately start spending LLM credits after the server starts.
# If this is off, running '/agent allow_action_choice true' will allow agents to start choosing actions, which must be done
# after every server restart
agentsCanStartChoosingActionsByDefault: No

# Whether a message should display above agent's heads explaining what they are doing right now
showWhatAgentsAreDoing: Yes

# Whether a message should display above agent's heads explaining their thought process for their most recent action
showThoughts: Yes

# The number of ticks that the thought message should be displayed for, if showThoughts is enabled. Default is 15 seconds (300 ticks)
showThoughtsTicks: 300

# The max distance (in blocks) that an agent can be from a Location in order to possibly execute actions bound to that Location
locationBoundActionRange: 7.0