# ----------------- LLMs begin --------------------

# The owner of the 'Large Language Model' that should be used. OpenAI by default due to ChatGPT.
# If you type "OpenAI":
# - Fill up the 'openAI_API_key'
llmModel: "OpenAI"

# Token for accessing OpenAI's models. You may generate an API token/key here: https://platform.openai.com/account/api-keys
# At the moment of writing this, you must have a paid subscription in order for your API keys to work
openAI_API_key: ""

# The ChatGPT model that this plugin should use
chatGPTModel: "gpt-3.5-turbo"
# ----------------- LLMs end --------------------

# The maximum distance (in blocks) in which agents can chat with each other. Agents who are too far away cannot engage in conversations
maxChatRange: 5

# Whether all chats between Social Agents should be broadcasted to the entire server as if it were normal players chatting, or if
# the chats should be solely displayed on top of agent's heads
chatBroadcast: Yes

# Whether agents should be loaded after a server restart.
# If set to 'No', then all agents disappear after a restart. They're still saved in the MineSocieties/social_agents directory, but
# the plugin will not automatically load them once it starts again.
loadSavedAgents: Yes