package ulisboa.tecnico.llms.prompts;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

public class SimplePromptTest extends CommonTest {

    @Test
    public void simplePromtTest() {
        String prompt = "What is the most common reply to 'Hello there!'?";
        String response = getManager().promptSync(prompt);

        System.out.println("Prompted ChatGPT with the prompt (" + prompt + "). Its response is:\n----\n" + response + "\n----");
    }

    @Test
    public void memoryTest() {
        // This test shows that ChatGPT does not remember past conversations. It's ok. It's fine. Don't cry...

        String prompt1 = "When I say 'Hello There', reply with 'General Kenobi'";
        String response1 = getManager().promptSync(prompt1);

        System.out.println("Prompted ChatGPT with the prompt (" + prompt1 + "). Its response is:\n----\n" + response1 + "\n----");

        String prompt2 = "Hello there!";
        String response2 = getManager().promptSync(prompt2);

        System.out.println("Prompted ChatGPT with the prompt (" + prompt2 + "). Its response is:\n----\n" + response2 + "\n----");
    }

    @Test
    public void foo() {
        String personalities = """
                Accepted
                Accepting
                Accomplished
                Affectionate
                Affirming
                Amazed
                Ambitious
                Amorous
                Amused
                Amusement
                Animated
                Appreciative
                Astonished
                Audacious
                Authentic
                Avid
                Awake
                Awed
                Blissful
                Bold
                Bouncy
                Brash
                Bright
                Bubbly
                Buoyant
                Calm
                Carefree
                Caring
                Charming
                Cheerful
                Cheery
                Chill
                Chilled
                Chipper
                Chuffed
                Cold
                Colorless
                Comfortable
                Comforted
                Comical
                Communicative
                Companionable
                Compassionate
                Complacent
                Composed
                Confident
                Contemplative
                Content
                Contented
                Cool
                Cordial
                Courageous
                Covetous
                Cranky
                Crappy
                Craving
                Creative
                Cross
                Curious
                Decisive
                Deep
                Delighted
                Demure
                Determined
                Dignified
                Dorky
                Dreamy
                Earnest
                Easy-Going
                Emotional
                Empathetic
                Empowered
                Energetic
                Energized
                Enlightened
                Enthralled
                Enthused
                Enthusiastic
                Euphoric
                Excited
                Exhilarated
                Exuberant
                Fantastic
                Fascinated
                Fearless
                Felicitousness
                Festive
                Flamboyant
                Flirty
                Focused
                Friendly
                Fulfilled
                Full
                Funny
                Geeky
                Giggly
                Good
                Gracious
                Grateful
                Gratitude
                Happy
                Harmonious
                Helpful
                High
                Honest
                Hope
                Hopeful
                Hospitable
                Hot
                Humorous
                Hungry
                Hyper
                Idyllic
                Imaginative
                Important
                Impressed
                Inclusive
                Indescribable
                Infatuated
                Inspiration
                Inspired
                Interest
                Interested
                Introspective
                Invigorated
                Jovial
                Joyful
                Joyous
                Jubilant
                Kind
                Liberated
                Liberating
                Light
                Lighthearted
                Lively
                Love
                Loved
                Loving
                Meditative
                Mellow
                Merry
                Moody
                Motivated
                Mystified
                Nerdy
                Nostalgic
                Open
                Optimistic
                Outgoing
                Passionate
                Peaceful
                Pensive
                Peppy
                Perseverant
                Philosophical
                Playful
                Pleasant
                Pleased
                Pompous
                Positive
                Powerful
                Proud
                Pumped
                Quiet
                Radiant
                Realistic
                Reflective
                Refreshed
                Rejuvenated
                Relaxed
                Relieved
                Renewed
                Reserved
                Reverent
                Romantic
                Safe
                Sanguine
                Satiated
                Satisfied
                Sedated
                Sentimental
                Serene
                Serenity
                Settled
                Shocked
                Sleepy
                Smart
                Snappy
                Sociable
                Sparkling
                Spirited
                Sunny
                Sympathetic
                Talkative
                Tender
                Thankful
                Thoughtful
                Thrilled
                Touched
                Tranquility
                Triumphant
                Troubled
                Trustful
                Understanding
                Unfeeling
                Unhappy
                Untroubled
                Upbeat
                Vibrant
                Vigorous
                Vivacious
                Warm
                Welcoming
                Whimsical
                Wistful
                Withdrawn
                Witty
                Wretched
                Yearning
                Zen
                Abandoned
                Aflutter
                Afraid
                Aggravated
                Aggrieved
                Agitated
                Alienated
                Alone
                Aloof
                Angry
                Annoyed
                Annoying
                Antagonistic
                Antsy
                Anxious
                Apathetic
                Apprehensive
                Argumentative
                Arrogant
                Ashamed
                Awe
                Baffled
                Barren
                Belligerent
                Bemused
                Betrayed
                Bewildered
                Bitter
                Blank
                Blue
                Bored
                Bothered
                Brooding
                Brutal
                Callous
                Cantankerous
                Capricious
                Chapfallen
                Cold
                Combative
                Complacent
                Confining
                Confrontational
                Confused
                Cranky
                Crappy
                Crazy
                Cruel
                Crushed
                Cynical
                Dark
                Dead
                Defeated
                Deflated
                Dejected
                Demoralized
                Depleted
                Depressed
                Desolate
                Despairing
                Desperate
                Despondent
                Destitute
                Detached
                Devious
                Devoid
                Devouring
                Difficult
                Dirty
                Disappointed
                Discontent
                Discontented
                Disgruntled
                Disheartened
                Disheartening
                Dismayed
                Dispirited
                Dispiriting
                Distant
                Distressed
                Distrustful
                Dither
                Ditzy
                Down
                Downcast
                Drained
                Dreadful
                Dreary
                Drunk
                Dysphoric
                Eager
                Edgy
                Elated
                Embarrassed
                Empty
                Enraged
                Envious
                Erratic
                Exanimate
                Exasperated
                Exhausted
                Famished
                Fatalistic
                Fearful
                Foreboding
                Fretful
                Frightened
                Frustrated
                Frustrating
                Futile
                Giddy
                Gloomy
                Glum
                Goofy
                Gorged
                Gormandizing
                Grief-Stricken
                Grim
                Groggy
                Grumpy
                Guilty
                Hangry
                Haunting
                Heartbroken
                Helpless
                Hesitant
                Hollow
                Hopeless
                Hostile
                Humiliated
                Impulsive
                Inconsolable
                Indifferent
                Indignant
                Inferior
                Inferiority
                Infuriated
                Insatiable
                Insecure
                Insidious
                Insolent
                Intimidated
                Irascible
                Irate
                Irritated
                Isolated
                Jealous
                Jittery
                Jumpy
                Lamentable
                Lazy
                Lethargic
                Listless
                Lonely
                Lonesome
                Lost
                Low
                Mad
                Madness
                Manipulative
                Mean
                Melancholy
                Merciless
                Mischievous
                Miserable
                Moody
                Morose
                Mournful
                Mysterious
                Naughty
                Negative
                Nervous
                Neurotic
                Nightmarish
                Numb
                Obsessed
                Ominous
                On Edge
                Ornery
                Ostentatious
                Outraged
                Overwhelmed
                Painful
                Panicked
                Pensive
                Perplexed
                Pesky
                Pessimistic
                Petrified
                Petulant
                Powerless
                Predatory
                Pretentious
                Pride
                Puzzled
                Quarrelsome
                Queasy
                Quiet
                Rash
                Ravenous
                Rebarbative
                Reckless
                Regretful
                Rejected
                Remorseful
                Remote
                Repellant
                Resentful
                Restless
                Rushed
                Sad
                Scared
                Self-Conscious
                Serious
                Shameful
                Shocked
                Sick
                Silly
                Sinister
                Skeptical
                Somber
                Sorrowful
                Starved
                Strange
                Stressed
                Sullen
                Suspenseful
                Suspicious
                Temperamental
                Tense
                Terrified
                Terrifying
                Threatened
                Threatening
                Tired
                Touchy
                Troubled
                Unattached
                Uncaring
                Uncertain
                Uncertainty
                Uncomfortable
                Uneasy
                Unfeeling
                Unfriendly
                Unhappy
                Uninterested
                Unmotivated
                Unnerved
                Unpredictable
                Unsettled
                Upbeat
                Uptight
                Useless
                Vacant
                Vengeful
                Violent
                Volatile
                Voracious
                Vulnerable
                Weary
                Weird
                Withdrawn
                Worried
                Wretched
                Calm
                Collected
                Composed
                Cool
                Curious
                Detached
                Easygoing
                Fair
                Focused
                Honest
                Impartial
                Indifferent
                Objective
                Open-Minded
                Patient
                Peaceful
                Poised
                Relaxed
                Respectful
                Serene
                Thoughtful
                Unbothered
                Unemotional
                Unfazed
                Unmoved
                Unperturbed
                Unruffled
                Absorbed
                Alert
                Bittersweet
                Competitive
                Contemplative
                Crabby
                Dyspeptic
                Eclectic
                Ecstatic
                Feminine
                Fiery
                Giving
                Human
                Hungry
                Hyper
                Hyperactive
                Indescribable
                Livid
                Masculine
                Okay
                Quixotic
                Recumbent
                Resilient
                Sexy
                Shy
                Snobbish
                Surprised
                Whimsical
                """;

        String[] split = personalities.split("[ |\n]");

        System.out.println(Arrays.stream(split).filter(s -> !s.isEmpty()).map(s -> "\n" + s.toUpperCase()).toList());
    }
}
